server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /docs/auth
      - name: user-service
        url: /docs/user
      - name: leave-request-service
        url: /docs/leave
      - name: attendance-service
        url: /docs/attendance

      - name: notification-service
        url: /docs/notification



spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      default-filters:
        - name: PreserveHostHeader

      routes:
        # AUTH
        - id: auth-docs
          uri: http://localhost:8081
          predicates:
            - Path=/docs/auth
          filters:
            - SetPath=/v3/api-docs

        # USER
        - id: user-docs
          uri: http://localhost:8082
          predicates:
            - Path=/docs/user
          filters:
            - SetPath=/v3/api-docs

        # LEAVE
        - id: leave-docs
          uri: http://localhost:8083
          predicates:
            - Path=/docs/leave
          filters:
            - SetPath=/v3/api-docs

        # ATTENDANCE
        - id: attendance-docs
          uri: http://localhost:8084
          predicates:
            - Path=/docs/attendance, /docs/attendance/**
          filters:
            - SetPath=/v3/api-docs

        # NOTIFICATION
        - id: notification-docs
          uri: http://localhost:8085
          predicates:
            - Path=/docs/notification, /docs/notification/**
          filters:
            - SetPath=/v3/api-docs


  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mySecretKey

logging:
  level:
    org:
      springframework:
        security: DEBUG