server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: user-service
        url: /v3/api-docs/user
      - name: leave-request-service
        url: /v3/api-docs/leave
      - name: attendance-service
        url: /v3/api-docs/attendance
      - name: notification-service
        url: /v3/api-docs/notifications


spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      default-filters:
        - name: PreserveHostHeader

      routes:
        # ===================== LEAVE REQUEST SERVICE =====================
        - id: leave-request-service
          uri: http://localhost:8083
          predicates:
            - Path=/leaves/**, /leave-types/**, /leave-balances/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

        # Forward leave-request-service docs
        - id: leave-request-docs
          uri: http://localhost:8083
          predicates:
            - Path=/v3/api-docs/leave
          filters:
            - RewritePath=/v3/api-docs/leave(?<segment>/?.*), /v3/api-docs${segment}

        # ===================== AUTH SERVICE =====================
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /users/**, /roles/**, /permissions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

        # Forward auth-service docs
        - id: auth-docs
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth(?<segment>/?.*), /v3/api-docs${segment}

        # ===================== USER SERVICE =====================
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/departments/**, /employees/**, /positions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

        # Forward user-service docs
        - id: user-docs
          uri: http://localhost:8082
          predicates:
            - Path=/v3/api-docs/user, /v3/api-docs/user/**
          filters:
            - RewritePath=/v3/api-docs/user(?<segment>/?.*), /v3/api-docs${segment}

        # ===================== ATTENDANCE SERVICE =====================
        - id: attendance-service
          uri: http://localhost:8085
          predicates:
            - Path=/attendances/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        # Forward attendance-service docs
        - id: attendance-docs
          uri: http://localhost:8085
          predicates:
            - Path=/v3/api-docs/attendance
          filters:
            - RewritePath=/v3/api-docs/attendances(?<segment>/?.*), /v3/api-docs${segment}

        # ===================== NOTIFICATION SERVICE =====================
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notifications/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        # Forward notification-service docs
        - id: notification-docs
          uri: http://localhost:8086
          predicates:
            - Path=/v3/api-docs/notifications
          filters:
            - RewritePath=/v3/api-docs/notifications(?<segment>/?.*), /v3/api-docs${segment}


  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mySecretKey

logging:
  level:
    org:
      springframework:
        security: DEBUG