version: "3.9"

services:
  attendance-service:
    image: attendance-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://attendance-db:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_RABBITMQ_HOST: rabbitmq   # ðŸ‘ˆ Connect to shared RabbitMQ
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - attendance-db
    networks:
      - hrms-net

  attendance-db:
    image: postgres:15
    container_name: attendance-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5435:5432"
    volumes:
      - attendance-db-data:/var/lib/postgresql/data
    networks:
      - hrms-net

volumes:
  attendance-db-data:

networks:
  hrms-net:
    external: true
