version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_leave_request
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hrms_leavedb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  leave-request-service:
    image: leave-request-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leave-request-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_leave_request:5432/hrms_leavedb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_RABBITMQ_HOST: host.docker.internal   # ðŸ‘ˆ Connect to your manually running RabbitMQ
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    networks:
      - hrms-net

volumes:
  postgres-data:

networks:
  hrms-net:
    driver: bridge
